[package]
categories = [
    "cryptography::cryptocurrencies",
]
description = """
WIP
"""
keywords = [
    "zcash",
    "tachyon",
]
name = "zcash_tachyon"
version = "0.0.0"

documentation = "https://docs.rs/zcash_tachyon"
readme = "README.md"
repository = "https://github.com/tachyon-zcash/tachyon"

edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = [
    "std",
]
std = [
    "blake2b_simd/std",
    "ragu/std",
    "reddsa/std",
    "corez/std",
    "ragu/multicore",
]

[lints]
workspace = true

[dependencies]
blake2b_simd = { version = "1.0", default-features = false }
corez = { version = "0.1.1", default-features = false, features = [
    "alloc",
] }
derive_more = { version = "~2.1", default-features = false, features = [
    "full", # todo: use more specific features
] }
ff = "0.14"
group = "0.14"
lazy_static = { version = "1", default-features = false, features = [
    "spin_no_std",
] }
pasta_curves = { package = "zakura-pasta-curves", version = "1.0.0-rc.2" }
ragu = { git = "https://github.com/TalDerei/ragu", rev = "e5d71c2fb6194f9b654c5d275dae8b7c73aba9bd", default-features = false, features = [
    "mock",
] }

rand_core = { version = "0.10", default-features = false }
reddsa = { package = "zakura-reddsa", version = "1.0.0-rc.2", default-features = false }

[dev-dependencies]
rand = "0.10"

[lib]
bench = false
