# test code
allow-expect-in-tests = true           # expect_used
allow-indexing-slicing-in-tests = true # indexing_slicing
allow-panic-in-tests = true            # panic
allow-unwrap-in-tests = true           # unwrap_used

# const code
allow-expect-in-consts = true             # expect_used
allow-unwrap-in-consts = true             # unwrap_used
suppress-restriction-lint-in-const = true # indexing_slicing

# naming
allow-exact-repetitions = true # module_name_repetitions
