use corez::io::{self, Read, Write};
use derive_more::{Debug, Display, Eq as TotalEq, Error, From, Into, PartialEq};
use ff::Field as _;
use group::Curve as _;
use pasta_curves::{Eq, Fp, arithmetic::CurveAffine as _};

use super::{EpochIndex, TachygramSetCommit};
use crate::{digest::poseidon, serialization};

/// Running anchor over the consensus state.
///
/// A Poseidon hash sequence with three domain-separated link types:
///
/// - [`Anchor::next_stamp`] (`Tachyon-StampFld`) absorbs one stamp's
///   tachygram-set commitment.
/// - [`Anchor::next_empty`] (`Tachyon-EmptyBlk`) advances through one block
///   that contains zero stamps, preserving per-height anchor uniqueness.
/// - [`Anchor::next_epoch`] (`Tachyon-EpochStp`) lifts across an epoch
///   boundary; checked against a boundary chain's root by `SpendableInit`.
///
/// Opening reveals each link's role by its domain.
#[derive(Clone, Copy, Debug, From, Into, PartialEq, TotalEq)]
pub struct Anchor(pub Fp);

/// Errors from anchor advancement.
#[derive(Clone, Copy, Debug, Display, Error)]
pub enum AnchorError {
    /// The stamp commitment is the identity point, so it has no affine
    /// coordinates to absorb.
    #[display("stamp commitment is the identity point")]
    IdentityCommitment,
}

impl Anchor {
    /// Advance the anchor by absorbing one stamp's commit.
    ///
    /// Fails if `stamp_commit` is the identity point, which has no affine
    /// coordinates to absorb.
    ///
    /// Honest [`TachygramSetPoly`](crate::TachygramSetPoly) commitments
    /// generated by this crate should not be identity. The committed set
    /// polynomial is monic, so an identity commitment would correspond to a
    /// nontrivial linear relation among the fixed commitment generators.
    pub fn next_stamp(self, stamp_commit: &TachygramSetCommit) -> Result<Self, AnchorError> {
        let point = Eq::from(*stamp_commit).to_affine();
        let coords = point
            .coordinates()
            .into_option()
            .ok_or(AnchorError::IdentityCommitment)?;
        Ok(Self(poseidon::anchor_stamp_step(self.0, coords)))
    }

    /// Advance the anchor through one empty block (zero stamps).
    #[must_use]
    pub fn next_empty(self) -> Self {
        Self(poseidon::anchor_empty_step(self.0))
    }

    /// Lift the anchor across an epoch boundary into the new epoch's
    /// initial state.
    #[must_use]
    pub fn next_epoch(self, new_epoch: EpochIndex) -> Self {
        Self(poseidon::anchor_epoch_step(self.0, new_epoch))
    }

    /// Read a 32-byte anchor.
    pub fn read<R: Read>(mut reader: R) -> io::Result<Self> {
        serialization::read_fp(&mut reader).map(Self)
    }

    /// Write a 32-byte anchor.
    pub fn write<W: Write>(&self, mut writer: W) -> io::Result<()> {
        serialization::write_fp(&mut writer, &self.0)
    }
}

impl Default for Anchor {
    /// The genesis epoch boundary.
    fn default() -> Self {
        Self(Fp::ZERO).next_epoch(EpochIndex(0))
    }
}

#[cfg(test)]
mod tests {
    use group::Group as _;
    use rand::{SeedableRng as _, rngs::StdRng};

    use super::*;
    use crate::{Tachygram, TachygramSetPoly};

    /// Folding the same stamps in the same order yields the same anchor.
    #[test]
    fn next_stamp_is_deterministic() {
        let rng = &mut StdRng::seed_from_u64(0);
        let first = TachygramSetPoly::from_iter([Tachygram::from(Fp::random(&mut *rng))]).commit();
        let second = TachygramSetPoly::from_iter([Tachygram::from(Fp::random(&mut *rng))]).commit();

        let run_one = Anchor::default()
            .next_stamp(&first)
            .expect("non-identity")
            .next_stamp(&second)
            .expect("non-identity");
        let run_two = Anchor::default()
            .next_stamp(&first)
            .expect("non-identity")
            .next_stamp(&second)
            .expect("non-identity");
        assert_eq!(run_one, run_two);
    }

    /// Two distinct stamp commits absorb to distinct anchors.
    #[test]
    fn distinct_stamps_distinct_anchors() {
        let rng = &mut StdRng::seed_from_u64(0);
        let first = TachygramSetPoly::from_iter([Tachygram::from(Fp::random(&mut *rng))]).commit();
        let second = TachygramSetPoly::from_iter([Tachygram::from(Fp::random(&mut *rng))]).commit();

        assert_ne!(
            Anchor::default().next_stamp(&first).expect("non-identity"),
            Anchor::default().next_stamp(&second).expect("non-identity"),
        );
    }

    /// Order matters: absorbing the same stamps in different orders diverges.
    #[test]
    fn order_matters() {
        let rng = &mut StdRng::seed_from_u64(0);
        let first = TachygramSetPoly::from_iter([Tachygram::from(Fp::random(&mut *rng))]).commit();
        let second = TachygramSetPoly::from_iter([Tachygram::from(Fp::random(&mut *rng))]).commit();

        let forward = Anchor::default()
            .next_stamp(&first)
            .expect("non-identity")
            .next_stamp(&second)
            .expect("non-identity");
        let reverse = Anchor::default()
            .next_stamp(&second)
            .expect("non-identity")
            .next_stamp(&first)
            .expect("non-identity");
        assert_ne!(forward, reverse);
    }

    /// An empty-block tick changes the anchor.
    #[test]
    fn next_empty_advances_anchor() {
        let start = Anchor::default();
        assert_ne!(start, start.next_empty());
    }

    /// Consecutive empty-block ticks produce distinct anchors.
    #[test]
    fn consecutive_empty_distinct() {
        let first = Anchor::default().next_empty();
        let second = first.next_empty();
        assert_ne!(first, second);
    }

    /// Empty-block tick is domain-separated from stamp absorption.
    #[test]
    fn next_empty_distinct_from_next_stamp() {
        let rng = &mut StdRng::seed_from_u64(0);
        let stamp = TachygramSetPoly::from_iter([Tachygram::from(Fp::random(&mut *rng))]).commit();
        let via_empty = Anchor::default().next_empty();
        let via_stamp = Anchor::default().next_stamp(&stamp).expect("non-identity");
        assert_ne!(via_empty, via_stamp);
    }

    /// The identity commitment is rejected instead of panicking.
    #[test]
    fn next_stamp_rejects_identity_commitment() {
        let identity = TachygramSetCommit::from(Eq::identity());
        let err = Anchor::default().next_stamp(&identity).unwrap_err();
        let AnchorError::IdentityCommitment = err;
    }
}
