//! In-crate tests: independent Python-reference fixtures, permutation
//! sanity, and constant hygiene.
//!
//! Fixture provenance: every fixture below was generated by the independent
//! Python reference implementation (stdlib only), never by this crate.
//! Regeneration recipe:
//!
//! ```text
//! import hashlib
//! p = 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001
//! PERSON = b"Tachyon-MiMCx5v1"
//! def consts(r):
//!     out = [0]
//!     for i in range(1, r):
//!         h = hashlib.blake2b(i.to_bytes(8, "little"), digest_size=64,
//!                             person=PERSON).digest()
//!         out.append(int.from_bytes(h, "little") % p)
//!     return out
//! def mimc(k, x, cs):
//!     for c in cs:
//!         x = pow((x + k + c) % p, 5, p)
//!     return (x + k) % p
//! ```
//!
//! All limbs are little-endian `u64`s as consumed by `Fp::from_raw`.

extern crate alloc;

use alloc::vec::Vec;

use ff::{Field as _, PrimeField as _};
use pasta_curves::Fp;
use rand::{SeedableRng as _, rngs::StdRng};

use super::{ROUNDS, encrypt, encrypt_rounds, round_constants};

/// Number of random samples per randomized test.
const SAMPLES: usize = 8;

/// `c_1` from the Python reference.
const EXPECTED_C1: Fp = Fp::from_raw([
    0xab71_a1f8_c93a_9d47,
    0x2ab1_a7c0_c80b_eb1c,
    0x1b15_535d_dcba_6422,
    0x074c_f4d2_38ee_9f54,
]);

/// `c_5` from the Python reference.
const EXPECTED_C5: Fp = Fp::from_raw([
    0x7c7c_dd4f_ae01_4c89,
    0x03bc_9cd9_e9a7_7339,
    0x86fd_6a01_11ff_ea18,
    0x0656_9ee5_8ffc_018c,
]);

/// `c_109` from the Python reference.
const EXPECTED_C109: Fp = Fp::from_raw([
    0xc471_d487_dab1_5899,
    0x2dd4_0242_661a_9035,
    0x93b8_d039_b379_2a5e,
    0x3796_e41a_65a6_a541,
]);

/// `p - 1`, the largest field element.
const P_MINUS_ONE: Fp = Fp::from_raw([
    0x992d_30ed_0000_0000,
    0x2246_98fc_094c_f91b,
    0x0000_0000_0000_0000,
    0x4000_0000_0000_0000,
]);

/// `p - 2`.
const P_MINUS_TWO: Fp = Fp::from_raw([
    0x992d_30ec_ffff_ffff,
    0x2246_98fc_094c_f91b,
    0x0000_0000_0000_0000,
    0x4000_0000_0000_0000,
]);

/// `5^{-1} mod (p - 1)`, the inverse exponent of `x^5` over `Fp`.
///
/// Derivation (Python): `pow(5, -1, p - 1)` with
/// `p = 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001`,
/// giving
/// `0x333333333333333333333333333333334e9ee0c9a10a60e2e0f0f3f0cccccccd`.
/// Limbs are little-endian `u64`s as consumed by `ff::Field::pow`.
const INV_FIVE_EXPONENT: [u64; 4] = [
    0xe0f0_f3f0_cccc_cccd,
    0x4e9e_e0c9_a10a_60e2,
    0x3333_3333_3333_3333,
    0x3333_3333_3333_3333,
];

#[test]
fn pinned_round_constants_match_python_reference() {
    let constants = round_constants::<ROUNDS>();
    assert_eq!(
        constants[1], EXPECTED_C1,
        "c_1 drifted from the Python reference"
    );
    assert_eq!(
        constants[5], EXPECTED_C5,
        "c_5 drifted from the Python reference"
    );
    assert_eq!(
        constants[109], EXPECTED_C109,
        "c_109 drifted from the Python reference"
    );
}

#[test]
fn encrypt_matches_python_reference_at_deployed_rounds() {
    // (key, input, ciphertext) triples at r = 110, from the Python reference.
    let vectors = [
        (
            Fp::ZERO,
            Fp::ZERO,
            Fp::from_raw([
                0xf9aa_d578_1f5d_db0d,
                0x72e9_9c9b_0c68_15db,
                0x698e_89ee_3045_cf6b,
                0x13fc_8119_a044_394d,
            ]),
        ),
        (
            Fp::from_raw([1u64, 0u64, 0u64, 0u64]),
            Fp::from_raw([2u64, 0u64, 0u64, 0u64]),
            Fp::from_raw([
                0xae7a_71b8_ae35_cce7,
                0x70c3_4b93_1106_8269,
                0xaeaa_1daa_6ec8_37a8,
                0x3edc_9ae9_953b_442f,
            ]),
        ),
        (
            P_MINUS_ONE,
            P_MINUS_TWO,
            Fp::from_raw([
                0x83df_9894_2c0b_f1a7,
                0xbec3_0e62_df71_a911,
                0xb596_6533_14f3_9c2c,
                0x00cc_0cac_ed6c_08c2,
            ]),
        ),
    ];

    for (key, input, expected) in vectors {
        assert_eq!(encrypt(key, input), expected, "r=110 vector mismatch");
    }
}

#[test]
fn encrypt_matches_python_reference_at_fifty_one_rounds() {
    // key = 1, x = 2 at r = 51, exercising the const-generic path at the
    // bottom of the contested round-count zone (#139).
    let key = Fp::from_raw([1u64, 0u64, 0u64, 0u64]);
    let input = Fp::from_raw([2u64, 0u64, 0u64, 0u64]);
    let expected = Fp::from_raw([
        0xe25e_dbb8_5d0a_1540,
        0x0a60_76ee_885d_0dd1,
        0x0cd9_bac7_e7c1_f2e5,
        0x16bb_bfe1_ee30_0c6b,
    ]);
    assert_eq!(
        encrypt_rounds::<51>(key, input),
        expected,
        "r=51 vector mismatch"
    );
}

#[test]
fn pow5_is_a_permutation() {
    let rng = &mut StdRng::seed_from_u64(0);
    for _ in 0..SAMPLES {
        let element = Fp::random(&mut *rng);
        let image = element.square().square().mul(&element);
        assert_eq!(
            image.pow(INV_FIVE_EXPONENT),
            element,
            "x^5 then x^(5^-1 mod p-1) must be the identity"
        );
    }
}

#[test]
fn round_constant_schedule_hygiene() {
    let constants = round_constants::<ROUNDS>();
    assert_eq!(constants.len(), ROUNDS, "schedule length must equal ROUNDS");
    assert_eq!(constants[0], Fp::ZERO, "c_0 must be zero");

    let mut reprs: Vec<[u8; 32]> = constants.iter().map(Fp::to_repr).collect();
    reprs.sort_unstable();
    reprs.dedup();
    assert_eq!(
        reprs.len(),
        ROUNDS,
        "round constants must be pairwise distinct"
    );
}

#[test]
fn distinct_keys_give_distinct_ciphertexts() {
    let rng = &mut StdRng::seed_from_u64(0);
    let input = Fp::random(&mut *rng);
    for _ in 0..SAMPLES {
        let key_a = Fp::random(&mut *rng);
        let key_b = Fp::random(&mut *rng);
        assert_ne!(key_a, key_b, "rng produced a key collision");
        assert_ne!(
            encrypt(key_a, input),
            encrypt(key_b, input),
            "distinct keys must give distinct ciphertexts"
        );
    }
}

#[test]
fn cached_path_matches_generic_path() {
    let rng = &mut StdRng::seed_from_u64(0);
    for _ in 0..SAMPLES {
        let key = Fp::random(&mut *rng);
        let input = Fp::random(&mut *rng);
        assert_eq!(
            encrypt(key, input),
            encrypt_rounds::<ROUNDS>(key, input),
            "cached and per-call schedules must agree"
        );
    }
}
