//! Each relation here is a convenience tool over the two framework hooks a step
//! body reaches for -- [`StepCtx::enforce_poly_query`] and
//! [`StepCtx::derive_challenge`]. They share one shape: the result is
//! prover-supplied (built off-circuit) rather than computed by the relation,
//! the relation computes each operand's commitment internally, derives a
//! Fiat-Shamir challenge `z` from those commitments, checks the defining
//! algebraic identity at `z`, and emits one opening claim per operand at
//! `(commitment, z, eval(z))`. These functions only *record* the openings;
//! actually verifying them is the proof system's job, not done here.
//!
//! Soundness rests on Schwartz-Zippel: every operand commitment is absorbed
//! into `z`, so the operands are fixed *before* `z` exists and the identity at
//! a random `z` pins the corresponding polynomial identity (error `~deg/|F|`).
//! An input that is **not** a committed operand (a raw scalar, say) is not
//! absorbed into `z` and is not pinned this way; a relation that takes such an
//! input states its own precondition.
//!
//! # Caller obligation: binding
//!
//! These relations prove the identity among the polynomials passed; pinning
//! *which* polynomials those are is the caller's job. Every operand the
//! surrounding statement relies on must have its commitment grounded in a
//! statement-fixed value -- a public input, a prior-step output, a
//! transcript/header-absorbed value, or a consensus/output-checked commitment
//! -- and the binding holds only once that chain actually terminates in such a
//! value (a fresh witness, or a commitment merely threaded onward, is not
//! itself enough). The binding target is the commitment *point*
//! (`= operand.commit()`); trailing-zero coefficients collapse under
//! [`Polynomial::commit`], so this is commitment-identity, not the literal
//! coefficient vector.
//!
//! This principle is common to all of these relations; each states which
//! operands it covers and any relation-specific nuance.
//!
//! Implementation invariant: the eval fed to each identity check is the same
//! eval emitted in that operand's opening claim (one `operand.eval(z)` call per
//! operand). A refactor that recomputed or separately witnessed the evals could
//! let the checked value diverge from the opened one and break soundness.

use ff::Field as _;
use pasta_curves::{Eq, Fp};
use ragu::{Error, Result, ctx::StepCtx, polynomial::Polynomial};

use super::subgroup_generator;
use crate::constants::POLY_LEN_MAX;

/// Evaluate at `position` the unique polynomial of degree below `ORDER` that
/// takes `values[i]` at node `i` and is zero at every other `ORDER`-th root of
/// unity.
///
/// The nodes start at `node_start` and step by a primitive `VALUES`-th root
/// (computed internally), the spacing that lands them on the `ORDER`-th roots.
/// A *full* set (`VALUES = ORDER`, `node_start = 1`) covers every root; a
/// *sparse* set covers a sub-coset and is zero elsewhere. `vanishing` is the
/// `position^ORDER - 1` factor of the closed form, taken as an argument so a
/// caller that already holds it (the relation's domain divisor) does not
/// recompute it; callers must pass exactly `position^ORDER - 1`. Closed-form
/// subgroup-Lagrange interpolation, one inversion per node, with `n` = `ORDER`,
/// point `x` = `position`, nodes `a_i`, and values `v_i`:
///
/// $$
///     \sum_i v_i \, \frac{a_i}{x - a_i} \cdot \frac{x^{\,n} - 1}{n}.
/// $$
fn subgroup_interpolate<const ORDER: usize, const VALUES: usize>(
    values: &[Fp; VALUES],
    node_start: Fp,
    position: Fp,
    vanishing: Fp,
) -> Fp {
    const {
        assert!(ORDER != 0, "subgroup order must be nonzero");
    }

    #[expect(clippy::as_conversions, reason = "const order fits u64")]
    let prefactor = vanishing
        * Fp::from(ORDER as u64)
            .invert()
            .expect("subgroup order must be nonzero");

    let node_step = subgroup_generator::<VALUES>();
    let mut accumulator = Fp::ZERO;
    let mut node = node_start;
    for &value in values {
        let denominator = (position - node)
            .invert()
            .expect("position should not coincide with a node");

        accumulator += value * node * denominator;
        node *= node_step;
    }
    accumulator * prefactor
}

/// Evaluate `position^ORDER - 1`, whose roots are exactly the `ORDER`-th roots
/// of unity: zero on that subgroup, nonzero elsewhere.
fn zeroizer<const ORDER: usize>(position: Fp) -> Fp {
    #[expect(clippy::as_conversions, reason = "const order fits u64")]
    let power = position.pow_vartime([ORDER as u64]);
    power - Fp::ONE
}

/// Prove that the committed `matrix` advances along each row by a fixed power
/// map. Read its domain evaluations row-major as rows of `COLUMNS` cells, over
/// the order-`POLY_LEN_MAX` domain generated by `g`, so the cell after the one
/// at `z` sits at $gz$. Each cell is the previous one plus its `offsets` term,
/// raised to the power `exponent`; the row's final cell is exempt, since its
/// successor starts a fresh row. As an identity at the Fiat-Shamir point `z`
/// (with `|D|` = `POLY_LEN_MAX`, `M` = `matrix`, `e` = `exponent`, mask $m$
/// vanishing on the final column, and offset $o$ interpolating `offsets`):
///
/// $$
///     m(z) \bigl( M(gz) - (M(z) + o(z))^{\,e} \bigr) = Q(z) \, (z^{|D|} - 1).
/// $$
///
/// The mask and offset are public closed forms in `z`. The quotient `Q` is
/// carried as `SPLITS` capacity-wide splits, about as many as the masked map's
/// degree $\approx e \, |D|$ requires. The relation derives `z` from `matrix`
/// and the splits, opens `matrix` at `z` and $gz$, recombines `Q(z)`, and
/// checks the identity.
///
/// # Caller obligations (soundness)
///
/// - **Binding.** `matrix` and every split must be commitment-bound to a
///   statement-fixed value (public input, prior-step output, or
///   transcript-absorbed commitment, not a fresh witness); all feed `z`.
/// - **Public structure.** `offsets` and `exponent` are not absorbed into `z`;
///   they must be statement-fixed, never witness-chosen after `z`.
pub(crate) fn enforce_row_recurrence<const COLUMNS: usize, const SPLITS: usize>(
    ctx: &mut StepCtx<'_>,
    matrix: &Polynomial,
    quotient: &[Polynomial; SPLITS],
    offsets: &[Fp; COLUMNS],
    exponent: u64,
) -> Result<()> {
    let matrix_commit = matrix.commit();
    let quotient_commits: [Eq; SPLITS] = quotient.each_ref().map(Polynomial::commit);

    let z =
        ctx.derive_challenge(&[[matrix_commit].as_slice(), quotient_commits.as_slice()].concat())?;
    let vanishing = zeroizer::<POLY_LEN_MAX>(z);

    let matrix_at_z = matrix.eval(z);
    ctx.enforce_poly_query(matrix_commit, z, matrix_at_z)?;

    let quotient_at_z = {
        let stride = vanishing + Fp::ONE;
        let mut quotient_at_z = Fp::ZERO;
        let mut shift = Fp::ONE;
        for qt_p in quotient {
            let eval = qt_p.eval(z);
            ctx.enforce_poly_query(qt_p.commit(), z, eval)?;
            quotient_at_z += shift * eval;
            shift *= stride;
        }
        quotient_at_z
    };

    let znext = subgroup_generator::<POLY_LEN_MAX>() * z;
    let matrix_at_znext = matrix.eval(znext);
    ctx.enforce_poly_query(matrix_commit, znext, matrix_at_znext)?;

    #[expect(
        clippy::as_conversions,
        clippy::integer_division,
        clippy::integer_division_remainder_used,
        reason = "COLUMNS divides POLY_LEN_MAX; quotient fits u64"
    )]
    let period_position = z.pow_vartime([(POLY_LEN_MAX / COLUMNS) as u64]);

    // Mask end-of-row discontinuity at `g_sub^{COLUMNS-1} = g_sub^{-1}`
    let mask = period_position
        - subgroup_generator::<COLUMNS>()
            .invert()
            .expect("a root of unity is nonzero");

    // The offset interpolation's `position^COLUMNS - 1` factor is
    // `period_position^COLUMNS = z^|D|`, so its vanishing is the shared one.
    let offset =
        subgroup_interpolate::<COLUMNS, COLUMNS>(offsets, Fp::ONE, period_position, vanishing);

    let residual = matrix_at_znext - (matrix_at_z + offset).pow_vartime([exponent]);

    if mask * residual != quotient_at_z * vanishing {
        return Err(Error::InvalidWitness(
            "row recurrence identity fails at challenge".into(),
        ));
    }
    Ok(())
}

/// Prove the row-wise power-map recurrence of [`enforce_row_recurrence`] with
/// the per-step offset carried as *committed* polynomials rather than
/// `COLUMNS` public scalars: a committed constant schedule plus a `FULL`-wide
/// cyclic key schedule reconstructed inline from `PARTS` committed part-key
/// polynomials. The committed-operand face of the row recurrence, for callers
/// whose key schedule exists only behind a commitment, where materializing
/// the offsets as scalars would cost one opening per key.
///
/// Read the `matrix` domain evaluations row-major as rows of `COLUMNS` cells
/// over the order-`POLY_LEN_MAX` domain (`COLUMNS = POLY_LEN_MAX` degenerates
/// to a flat single-row recurrence over the whole domain). The offset is
/// `O(z) = C(z) + K(ζ·z^{|D|/κ})`, `κ = FULL`: `constants` is the committed
/// `C` (the public constant schedule, opened at `z`), and the order-`κ` key
/// interpolant `K` is the `P = PARTS` part schedules interleaved on the `P`
/// cosets of `⟨ζ⟩`,
///
/// $$ K(x) = \sum_{p=0}^{P-1} s_p(x)\,A_p\!\left(x\,ζ^{-p}\right),\quad
///    s_p(x) = \tfrac{1}{P}\sum_{j=0}^{P-1} ω_P^{-pj}\,\bigl(x^{κ/P}\bigr)^{j},
/// $$
///
/// with `ω_P` a primitive `P`-th root and `A_p` the eval-form part-key poly
/// over the order-`κ/P` subgroup (`A_p(ζ^{P·r}) = k_{P·r+p}`). The `s_p` are
/// the inverse-DFT coset indicators (`s_p(ζ^m) = [m ≡ p mod P]`), so this is
/// an exact degree-`<κ` polynomial identity: reconstructing `K(ζ·z^{|D|/κ})`
/// needs one opening of each `A_p` (at `key_point·ζ^{-p}`) plus the public
/// selectors — no merged key commitment and no quotient (`PARTS = 1`
/// collapses to a single opening of the whole schedule). As an identity at
/// the Fiat-Shamir point `z` (`|D|` = `POLY_LEN_MAX`, mask $m$ vanishing on
/// the final column as in the row recurrence):
///
/// $$
///     m(z) \bigl( M(gz) - (M(z) + O(z))^{\,e} \bigr) = Q(z) \, (z^{|D|} - 1).
/// $$
///
/// The quotient `Q` is carried as `SPLITS` capacity-wide splits. The offset
/// needs no per-node inversion and is independent of `κ`, so a full-length
/// key schedule stays in budget.
///
/// # Caller obligations (soundness)
///
/// - **Binding.** `matrix`, `constants`, every `keys[p]`, and every split must
///   be commitment-bound to a statement-fixed value; all feed `z`. In
///   particular `constants` must be the public constant schedule (a circuit
///   constant, or pinned to it by commit-equality) and each `keys[p]` bound to
///   its certified schedule commitment, or the offset is a free witness and the
///   relation is vacuous.
/// - **Public structure.** `exponent` is fixed and not witness-chosen after
///   `z`. Part `p`'s poly is opened at `key_point·ζ^{-p}` (the coset
///   realignment); the `keys` order must match the part indices `0..P`, or the
///   reconstruction is wrong. The key schedule cycles with position, not per
///   row: keep `FULL` a divisor of `COLUMNS` so every row sees the same key
///   phase.
pub(crate) fn enforce_committed_offset_recurrence<
    const COLUMNS: usize,
    const SPLITS: usize,
    const FULL: usize,
    const PARTS: usize,
>(
    ctx: &mut StepCtx<'_>,
    matrix: &Polynomial,
    quotient: &[Polynomial; SPLITS],
    constants: &Polynomial,
    keys: &[&Polynomial; PARTS],
    exponent: u64,
) -> Result<()> {
    let matrix_commit = matrix.commit();
    let constants_commit = constants.commit();
    let key_commits: [Eq; PARTS] = keys.each_ref().map(|key| key.commit());
    let quotient_commits: [Eq; SPLITS] = quotient.each_ref().map(Polynomial::commit);

    let z = ctx.derive_challenge(
        &[
            [matrix_commit, constants_commit].as_slice(),
            key_commits.as_slice(),
            quotient_commits.as_slice(),
        ]
        .concat(),
    )?;
    let vanishing = zeroizer::<POLY_LEN_MAX>(z);

    let matrix_at_z = matrix.eval(z);
    ctx.enforce_poly_query(matrix_commit, z, matrix_at_z)?;
    let constants_at_z = constants.eval(z);
    ctx.enforce_poly_query(constants_commit, z, constants_at_z)?;

    let quotient_at_z = {
        let stride = vanishing + Fp::ONE;
        let mut quotient_at_z = Fp::ZERO;
        let mut shift = Fp::ONE;
        for qt_p in quotient {
            let eval = qt_p.eval(z);
            ctx.enforce_poly_query(qt_p.commit(), z, eval)?;
            quotient_at_z += shift * eval;
            shift *= stride;
        }
        quotient_at_z
    };

    let znext = subgroup_generator::<POLY_LEN_MAX>() * z;
    let matrix_at_znext = matrix.eval(znext);
    ctx.enforce_poly_query(matrix_commit, znext, matrix_at_znext)?;

    #[expect(
        clippy::as_conversions,
        clippy::integer_division,
        clippy::integer_division_remainder_used,
        reason = "COLUMNS and FULL divide POLY_LEN_MAX, PARTS divides FULL; all fit u64"
    )]
    let (row_exponent, key_exponent, part_exponent, parts) = (
        (POLY_LEN_MAX / COLUMNS) as u64,
        (POLY_LEN_MAX / FULL) as u64,
        (FULL / PARTS) as u64,
        PARTS as u64,
    );

    // O(z) = C(z) + K(ζ·z^{|D|/κ}): committed constant schedule plus the
    // cyclic key value, reconstructed inline from the `PARTS` part-key polys
    // by the interleaved-coset identity `K(x) = Σ_p s_p(x)·A_p(x·ζ^{-p})`.
    // Each `A_p` interpolates part `p` over `⟨ζ^P⟩`; `s_p` is the inverse-DFT
    // indicator of coset `p`. `y = key_point^{κ/P}` maps `⟨ζ⟩` onto the
    // `P`-th roots, where `s_p(x) = (1/P)·Σ_j (ω_P^{-p}·y)^j`.
    let zeta = subgroup_generator::<FULL>();
    let key_point = zeta * z.pow_vartime([key_exponent]);
    let zeta_inv = zeta.invert().expect("a root of unity is nonzero");
    let part_root_inv = subgroup_generator::<PARTS>()
        .invert()
        .expect("a root of unity is nonzero");
    let parts_inv = Fp::from(parts).invert().expect("PARTS is invertible in Fp");
    let y = key_point.pow_vartime([part_exponent]);

    // Open each part `p` at `key_point·ζ^{-p}`, weight by `s_p(key_point)`.
    let mut key_at = Fp::ZERO;
    let mut point = key_point; // key_point·ζ^{-p}
    let mut root_negp = Fp::ONE; // ω_P^{-p}
    for (key, key_commit) in keys.iter().zip(key_commits) {
        let a_at = key.eval(point);
        ctx.enforce_poly_query(key_commit, point, a_at)?;
        let base = root_negp * y;
        let mut selector = Fp::ZERO;
        let mut term = Fp::ONE;
        for _ in 0..PARTS {
            selector += term;
            term *= base;
        }
        key_at += selector * parts_inv * a_at;
        point *= zeta_inv;
        root_negp *= part_root_inv;
    }
    let offset = constants_at_z + key_at;

    // Mask end-of-row discontinuity at `g_sub^{COLUMNS-1} = g_sub^{-1}`
    let mask = z.pow_vartime([row_exponent])
        - subgroup_generator::<COLUMNS>()
            .invert()
            .expect("a root of unity is nonzero");

    let residual = matrix_at_znext - (matrix_at_z + offset).pow_vartime([exponent]);

    if mask * residual != quotient_at_z * vanishing {
        return Err(Error::InvalidWitness(
            "committed-offset recurrence identity fails at challenge".into(),
        ));
    }
    Ok(())
}

/// Bind a low-degree polynomial `column` to a strided column of the committed
/// `matrix`. On the order-`SUB_ORDER` subgroup `⟨ζ⟩`
/// (`ζ = subgroup_generator::<SUB_ORDER>()`) the relation pins
/// `column(ζ^r) = matrix(stride·ζ^r) + offset`, i.e. `column` is the
/// degree-`<SUB_ORDER` interpolant of the `matrix` cells on the coset
/// `stride·⟨ζ⟩` (plus a constant `offset`). As an identity at the Fiat-Shamir
/// point `z`:
///
/// $$ \mathit{column}(z) - \mathit{offset} - \mathit{matrix}(\sigma z)
///    = Q(z)\,(z^{\mathrm{SUB\_ORDER}} - 1). $$
///
/// The numerator `column(X) − offset − matrix(σX)` vanishes on `⟨ζ⟩` exactly
/// when the column equality holds, so a pass at random `z` forces it
/// (Schwartz-Zippel). `column` and `matrix` are full polynomials; `Q` is a
/// single committed quotient.
///
/// # Caller obligations (soundness)
///
/// - **Binding.** `matrix`, `column`, and `quotient` must be commitment-bound
///   to statement-fixed values; all feed `z`.
/// - **Public structure.** `stride` and `offset` are statement-fixed, never
///   witness-chosen after `z`.
pub(crate) fn enforce_strided_column<const SUB_ORDER: usize>(
    ctx: &mut StepCtx<'_>,
    matrix: &Polynomial,
    column: &Polynomial,
    quotient: &Polynomial,
    stride: Fp,
    offset: Fp,
) -> Result<()> {
    let matrix_commit = matrix.commit();
    let column_commit = column.commit();
    let quotient_commit = quotient.commit();

    let z = ctx.derive_challenge(&[matrix_commit, column_commit, quotient_commit])?;

    let column_at_z = column.eval(z);
    ctx.enforce_poly_query(column_commit, z, column_at_z)?;
    let strided = stride * z;
    let matrix_at_strided = matrix.eval(strided);
    ctx.enforce_poly_query(matrix_commit, strided, matrix_at_strided)?;
    let quotient_at_z = quotient.eval(z);
    ctx.enforce_poly_query(quotient_commit, z, quotient_at_z)?;

    if column_at_z - offset - matrix_at_strided != quotient_at_z * zeroizer::<SUB_ORDER>(z) {
        return Err(Error::InvalidWitness(
            "strided column identity fails at challenge".into(),
        ));
    }
    Ok(())
}

/// Prove the witnessed running-sum accumulator `A` is the geometric Horner sum
/// of `values`' evaluations over the order-`ORDER` subgroup `⟨ζ⟩`, and return
/// the bound total `A(1) = Σ_{p<ORDER} values(ζ^p)·weight^p`.
///
/// `A` is the inclusive suffix sum `A(ζ^d) = Σ_{k≥d} values(ζ^k)·weight^{k-d}`,
/// so consecutive nodes relate by the *constant* Horner coefficient `weight`:
/// `A(x) − weight·A(ζx) − values(x) = 0` on `⟨ζ⟩` except the wrap node
/// `x = ζ^{ORDER-1}` (where `ζx` folds back to `1`). Masking that node gives
/// the identity at the Fiat-Shamir point `z`:
///
/// $$
///     (z - ζ^{ORDER-1})\bigl(A(z) - w\,A(ζz) - \mathit{values}(z)\bigr)
///     = Q(z)\,(z^{ORDER} - 1),
/// $$
///
/// with `w` = `weight`, plus the top boundary `A(ζ^{ORDER-1}) =
/// values(ζ^{ORDER-1})` pinning the downward cascade. Because `deg values,
/// deg A < ORDER`, the quotient `Q` is a single constant (no splits). The
/// pinned cascade fixes every subgroup-node value of `A`, so the returned
/// total `A(1)` (node `ζ^0`) is the genuine full sum regardless of `A`'s
/// degree.
///
/// # Caller obligations (soundness)
///
/// - **Binding.** `values`, `accumulator`, and `quotient` must be
///   commitment-bound to statement-fixed values; all feed `z`.
/// - **Public structure.** `weight` is statement-fixed (a challenge derived
///   over the operand commitments *before* this call), never witness-chosen
///   after `z`. The returned total is only as bound as `values` and `weight`.
pub(crate) fn enforce_evaluation_sum<const ORDER: usize>(
    ctx: &mut StepCtx<'_>,
    values: &Polynomial,
    accumulator: &Polynomial,
    quotient: &Polynomial,
    weight: Fp,
) -> Result<Fp> {
    let values_commit = values.commit();
    let accumulator_commit = accumulator.commit();
    let quotient_commit = quotient.commit();

    let z = ctx.derive_challenge(&[values_commit, accumulator_commit, quotient_commit])?;

    let zeta = subgroup_generator::<ORDER>();
    #[expect(clippy::as_conversions, reason = "const order fits u64")]
    let top = zeta.pow_vartime([ORDER as u64 - 1]);
    let znext = zeta * z;

    let values_at_z = values.eval(z);
    ctx.enforce_poly_query(values_commit, z, values_at_z)?;
    let accumulator_at_z = accumulator.eval(z);
    ctx.enforce_poly_query(accumulator_commit, z, accumulator_at_z)?;
    let accumulator_at_znext = accumulator.eval(znext);
    ctx.enforce_poly_query(accumulator_commit, znext, accumulator_at_znext)?;
    let quotient_at_z = quotient.eval(z);
    ctx.enforce_poly_query(quotient_commit, z, quotient_at_z)?;

    let residual = accumulator_at_z - weight * accumulator_at_znext - values_at_z;
    if (z - top) * residual != quotient_at_z * zeroizer::<ORDER>(z) {
        return Err(Error::InvalidWitness(
            "evaluation sum recurrence fails at challenge".into(),
        ));
    }

    // Top boundary `A(ζ^{ORDER-1}) = values(ζ^{ORDER-1})` pins the cascade base.
    let accumulator_at_top = accumulator.eval(top);
    ctx.enforce_poly_query(accumulator_commit, top, accumulator_at_top)?;
    let values_at_top = values.eval(top);
    ctx.enforce_poly_query(values_commit, top, values_at_top)?;
    if accumulator_at_top != values_at_top {
        return Err(Error::InvalidWitness(
            "evaluation sum top boundary fails at the wrap node".into(),
        ));
    }

    // The full inclusive sum is the node value `A(1) = A(ζ^0)`.
    let total = accumulator.eval(Fp::ONE);
    ctx.enforce_poly_query(accumulator_commit, Fp::ONE, total)?;
    Ok(total)
}

/// Pin the *first column* of the committed `matrix` to prescribed values. Read
/// its domain evaluations as a matrix; the first column is the `ROWS`-th roots
/// of unity (one cell per row), pinned to `base + values[row]`. As an identity
/// at the Fiat-Shamir point `z` (with `|D|` = `POLY_LEN_MAX`, `R` = `ROWS`,
/// `M` = `matrix`, `b` = `base`, selector $s$, and interpolant $v$ of
/// `values`):
///
/// $$
///     s(z) \bigl( M(z) - b - v(z) \bigr) = Q(z) \, (z^{|D|} - 1).
/// $$
///
/// The constraint binds only the first column, so it does not fit the bare
/// $Q \cdot Z_D$ form: the selector $s(z) = (z^{|D|} - 1) / (z^{R} - 1)$
/// carries the $z^{|D|} - 1$ factor the check re-introduces, leaving the column
/// vanisher $z^{R} - 1$ as the effective divisor. The `quotient` has degree
/// below `POLY_LEN_MAX`, so it is one committed polynomial; the relation
/// derives `z` from `matrix` and `quotient`, opens both at `z`, and checks the
/// identity.
///
/// Callers needing a non-affine boundary (such as pinning each cell to an S-box
/// of its row input) precompute the per-row target into `values`; the relation
/// pins the column to whatever interpolant `values` describes.
///
/// # Caller obligations (soundness)
///
/// - **Binding.** `matrix` and `quotient` must be commitment-bound to a
///   statement-fixed value (not a fresh or merely-threaded witness); both feed
///   `z`.
/// - **Public structure.** `base` and `values` are not absorbed into `z`; fix
///   them to statement-fixed values, never witness-chosen after `z`.
pub(crate) fn enforce_first_column_values<const ROWS: usize>(
    ctx: &mut StepCtx<'_>,
    matrix: &Polynomial,
    quotient: &Polynomial,
    base: Fp,
    values: &[Fp; ROWS],
) -> Result<()> {
    let matrix_commit = matrix.commit();
    let quotient_commit = quotient.commit();

    let z = ctx.derive_challenge(&[matrix_commit, quotient_commit])?;

    let matrix_at_z = matrix.eval(z);
    ctx.enforce_poly_query(matrix_commit, z, matrix_at_z)?;
    let quotient_at_z = quotient.eval(z);
    ctx.enforce_poly_query(quotient_commit, z, quotient_at_z)?;

    let domain_vanishing = zeroizer::<POLY_LEN_MAX>(z);
    let rows_vanishing = zeroizer::<ROWS>(z);

    let values_at_z = subgroup_interpolate::<ROWS, ROWS>(values, Fp::ONE, z, rows_vanishing);

    let complement = domain_vanishing
        * rows_vanishing
            .invert()
            .expect("random challenge should not be a first-column root of unity");

    if complement * (matrix_at_z - base - values_at_z) != quotient_at_z * domain_vanishing {
        return Err(Error::InvalidWitness(
            "first column values identity fails at challenge".into(),
        ));
    }
    Ok(())
}

/// Faithful polynomial product: confirm `product = multiplicand · multiplier`
/// among three committed polynomials by opening all three at a Fiat-Shamir
/// challenge.
///
/// `product` is prover-supplied and the relation works only from the three
/// commitments and their openings at `z` -- it does not multiply the inputs.
/// The point-wise identity `product(z) = multiplicand(z)·multiplier(z)` at a
/// random `z` confirms the relation: with every operand committed and absorbed
/// into `z`, the difference `product − multiplicand·multiplier` is a fixed
/// polynomial pinned to zero by Schwartz-Zippel.
///
/// # Caller obligation (soundness)
///
/// Every operand is committed and absorbed into `z`, so the module-level
/// binding obligation -- here applying symmetrically to `multiplicand`,
/// `multiplier`, and `product` -- is the only precondition.
pub(crate) fn enforce_poly_product(
    ctx: &mut StepCtx<'_>,
    multiplicand: &Polynomial,
    multiplier: &Polynomial,
    product: &Polynomial,
) -> Result<()> {
    let multiplicand_com = multiplicand.commit();
    let multiplier_com = multiplier.commit();
    let product_com = product.commit();
    let z = ctx.derive_challenge(&[multiplicand_com, multiplier_com, product_com])?;

    if product.eval(z) != multiplicand.eval(z) * multiplier.eval(z) {
        return Err(Error::InvalidWitness(
            "poly product: product identity fails at challenge".into(),
        ));
    }

    ctx.enforce_poly_query(multiplicand_com, z, multiplicand.eval(z))?;
    ctx.enforce_poly_query(multiplier_com, z, multiplier.eval(z))?;
    ctx.enforce_poly_query(product_com, z, product.eval(z))?;

    Ok(())
}

/// `X^exponent` evaluated at `point`.
#[expect(clippy::as_conversions, reason = "must be in range")]
fn monomial_at(point: Fp, exponent: usize) -> Fp {
    point.pow_vartime([exponent as u64])
}

/// Shifted linear combination of committed polynomials and monomials: confirm
/// `result(X) = Σ_i X^{k_i}·p_i(X) + Σ_j c_j·X^{m_j}` by opening each `p_i`
/// and `result` at a Fiat-Shamir challenge.
///
/// `result` is prover-supplied (built off-circuit). Each `shifted_polys` entry
/// pairs a committed operand `p_i` with its shift exponent `k_i`; each
/// `monomials` entry pairs a raw scalar coefficient `c_j` with its degree
/// `m_j`. The point-wise identity at a random `z` confirms the combination:
/// every polynomial operand is committed and absorbed into `z`, so the
/// difference of the two sides is a fixed polynomial pinned to zero by
/// Schwartz-Zippel.
///
/// # Caller obligations (soundness)
///
/// 1. **Binding.** Subject to the module-level binding obligation for every
///    `shifted_polys` entry and `result`. One nuance: `commit(X^k·p)` lands on
///    shifted generators, so it is not homomorphically recoverable from
///    `commit(p)`; a `result` consumed downstream must have its commitment
///    threaded independently.
/// 2. **Monomial coefficients fixed before the challenge.** The scalars `c_j`
///    are not absorbed into `z`, and the identity is *linear* in each: a prover
///    free to choose one after seeing `z` solves it and passes for any
///    committed `result`. Pin each coefficient independently of `z` -- a
///    public/statement input, a prior-step output, or a value absorbed into the
///    transcript before `z`.
/// 3. **Exponents.** The integer exponents `k_i` and `m_j` may be left free:
///    `z` is fixed by the commitments before any exponent is chosen, an
///    adaptive search over wrong exponents succeeds with probability `<=
///    tries/|F|`, and recovering an exponent from a `z` power is
///    discrete-log-hard. Whether a *specific* exponent is the one the
///    surrounding statement needs (an operand's span, say) is that statement's
///    obligation, as is any structural well-formedness of the operands (a
///    shifted sum proves the sum, not that the addends avoid overlapping).
///
/// The exponent parameters and the `z^k` point-wise factors stand in for
/// positional shifts the commitment scheme does not express directly; a
/// first-class committed `X^k·p` (or a built-in shifted sum) would carry the
/// shift itself and collapse this to a direct check.
pub(crate) fn enforce_shifted_combination<const SHIFTED_POLYS: usize, const MONOMIALS: usize>(
    ctx: &mut StepCtx<'_>,
    shifted_polys: [(&Polynomial, usize); SHIFTED_POLYS],
    monomials: [(Fp, usize); MONOMIALS],
    result: &Polynomial,
) -> Result<()> {
    let poly_coms = shifted_polys.map(|(poly, _)| poly.commit());
    let result_com = result.commit();
    let z = ctx.derive_challenge(&[poly_coms.as_slice(), [result_com].as_slice()].concat())?;

    let combination = shifted_polys
        .iter()
        .map(|&(poly, shift)| monomial_at(z, shift) * poly.eval(z))
        .chain(
            monomials
                .iter()
                .map(|&(coeff, degree)| coeff * monomial_at(z, degree)),
        )
        .sum::<Fp>();
    if result.eval(z) != combination {
        return Err(Error::InvalidWitness(
            "shifted combination: identity fails at challenge".into(),
        ));
    }

    for (&(poly, _), com) in shifted_polys.iter().zip(poly_coms) {
        ctx.enforce_poly_query(com, z, poly.eval(z))?;
    }
    ctx.enforce_poly_query(result_com, z, result.eval(z))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    //! Native checks of the shifted-combination identity on tiny cases.
    //!
    //! Pure algebra over explicit coefficient vectors: each case builds the
    //! operands with [`Polynomial::from_coeffs`], the true combination by
    //! coefficient arithmetic (an independent computation in the coefficient
    //! basis), and confirms the relation's defining identity point-wise (an
    //! exact polynomial identity holds at every point), plus one mismatch per
    //! operand kind.

    extern crate alloc;

    use alloc::{vec, vec::Vec};

    use super::*;

    /// Sample evaluation points (arbitrary, fixed).
    const POINTS: [u64; 3] = [0, 2, 927];

    fn poly(coeffs: &[u64]) -> Polynomial {
        Polynomial::from_coeffs(&coeffs.iter().copied().map(Fp::from).collect::<Vec<_>>())
    }

    /// `x^exponent` by repeated multiplication (exponents here are tiny).
    fn power(x: Fp, exponent: usize) -> Fp {
        (0..exponent).fold(Fp::ONE, |acc, _| acc * x)
    }

    /// The true combination, built in the coefficient basis.
    fn combine(shifted_polys: &[(&Polynomial, usize)], monomials: &[(Fp, usize)]) -> Polynomial {
        let len = shifted_polys
            .iter()
            .map(|&(poly, shift)| shift + poly.coefficients().len())
            .chain(monomials.iter().map(|&(_, degree)| degree + 1))
            .max()
            .unwrap_or(0);
        let mut coeffs = vec![Fp::ZERO; len];
        for &(poly, shift) in shifted_polys {
            for (position, coeff) in poly.coefficients().iter().enumerate() {
                coeffs[shift + position] += coeff;
            }
        }
        for &(coeff, degree) in monomials {
            coeffs[degree] += coeff;
        }
        Polynomial::from_coeffs(&coeffs)
    }

    /// The relation's point-wise check, at every sample point.
    fn identity_holds(
        shifted_polys: &[(&Polynomial, usize)],
        monomials: &[(Fp, usize)],
        result: &Polynomial,
    ) -> bool {
        POINTS.iter().all(|&point| {
            let x = Fp::from(point);
            let combination = shifted_polys
                .iter()
                .map(|&(poly, shift)| power(x, shift) * poly.eval(x))
                .chain(
                    monomials
                        .iter()
                        .map(|&(coeff, degree)| coeff * power(x, degree)),
                )
                .sum::<Fp>();
            result.eval(x) == combination
        })
    }

    #[test]
    fn identity_on_single_unshifted_polynomial() {
        let operand = poly(&[3, 5, 7]);
        let result = combine(&[(&operand, 0)], &[]);
        assert_eq!(result.coefficients(), operand.coefficients());
        assert!(identity_holds(&[(&operand, 0)], &[], &result));
    }

    #[test]
    fn identity_on_overlapping_shifted_polynomials() {
        let low = poly(&[3, 5, 7]);
        let high = poly(&[11, 13]);
        let terms = [(&low, 0), (&high, 1)];
        let result = combine(&terms, &[]);
        assert_eq!(result.coefficients(), poly(&[3, 16, 20]).coefficients());
        assert!(identity_holds(&terms, &[], &result));
    }

    #[test]
    fn identity_on_monomials_alone() {
        let monomials = [(Fp::from(5), 0), (Fp::from(9), 3)];
        let result = combine(&[], &monomials);
        assert_eq!(result.coefficients(), poly(&[5, 0, 0, 9]).coefficients());
        assert!(identity_holds(&[], &monomials, &result));
    }

    #[test]
    fn identity_on_cancelling_monomial() {
        // A negative monomial cancels a known coefficient: `low`'s top
        // coefficient `1` at degree 2 is overwritten by `high`'s first.
        let low = poly(&[3, 5, 1]);
        let high = poly(&[7, 11]);
        let terms = [(&low, 0), (&high, 2)];
        let monomials = [(-Fp::ONE, 2)];
        let result = combine(&terms, &monomials);
        assert_eq!(result.coefficients(), poly(&[3, 5, 7, 11]).coefficients());
        assert!(identity_holds(&terms, &monomials, &result));
    }

    #[test]
    fn identity_rejects_wrong_result() {
        let low = poly(&[3, 5]);
        let high = poly(&[7]);
        let wrong = poly(&[3, 5, 8]);
        assert!(!identity_holds(&[(&low, 0), (&high, 2)], &[], &wrong));
    }

    #[test]
    fn identity_rejects_wrong_monomial_coefficient() {
        let operand = poly(&[3, 5]);
        let result = combine(&[(&operand, 0)], &[(Fp::from(9), 2)]);
        assert!(!identity_holds(
            &[(&operand, 0)],
            &[(Fp::from(8), 2)],
            &result
        ));
    }

    #[test]
    fn identity_rejects_wrong_shift() {
        let low = poly(&[3, 5]);
        let high = poly(&[7]);
        let result = combine(&[(&low, 0), (&high, 2)], &[]);
        assert!(!identity_holds(&[(&low, 0), (&high, 3)], &[], &result));
    }

    /// Native checks of the homomorphic eval->coeff bind on a tiny order-4
    /// subgroup: an `A`/`Q` from [`evaluation_sum`] satisfies the masked
    /// recurrence and returns the genuine β-weighted total, and both the
    /// sentinel discharge and the recurrence reject a tampered operand.
    mod eval_sum {
        use super::*;
        use crate::relations::quotient::evaluation_sum;

        const ORDER: usize = 4;

        /// The masked recurrence `(x − ζ^{ORDER-1})(A(x) − β·A(ζx) − B(x)) =
        /// Q(x)(x^ORDER − 1)`, checked point-wise.
        fn recurrence_holds(
            leaf: &Polynomial,
            accumulator: &Polynomial,
            quotient: &Polynomial,
            beta: Fp,
            x: Fp,
        ) -> bool {
            let zeta = subgroup_generator::<ORDER>();
            let top = power(zeta, ORDER - 1);
            let residual = accumulator.eval(x) - beta * accumulator.eval(zeta * x) - leaf.eval(x);
            (x - top) * residual == quotient.eval(x) * (power(x, ORDER) - Fp::ONE)
        }

        #[test]
        fn accumulator_satisfies_the_masked_recurrence() {
            let leaf = poly(&[3, 5, 7, 11]);
            let beta = Fp::from(9);
            let (accumulator, quotient) = evaluation_sum::<ORDER>(leaf.coefficients(), beta);
            for &point in &POINTS {
                assert!(recurrence_holds(
                    &leaf,
                    &accumulator,
                    &quotient,
                    beta,
                    Fp::from(point)
                ));
            }
        }

        #[test]
        fn total_is_the_beta_weighted_leaf_sum() {
            let leaf = poly(&[3, 5, 7, 11]);
            let beta = Fp::from(9);
            let zeta = subgroup_generator::<ORDER>();
            let (accumulator, _quotient) = evaluation_sum::<ORDER>(leaf.coefficients(), beta);

            // A(1) is the inclusive β-weighted sum of B's subgroup values.
            let mut node = Fp::ONE;
            let mut weight = Fp::ONE;
            let mut expected = Fp::ZERO;
            for _ in 0..ORDER {
                expected += weight * leaf.eval(node);
                node *= zeta;
                weight *= beta;
            }
            assert_eq!(accumulator.eval(Fp::ONE), expected);

            // Top boundary: A(ζ^{ORDER-1}) = B(ζ^{ORDER-1}).
            let top = power(zeta, ORDER - 1);
            assert_eq!(accumulator.eval(top), leaf.eval(top));
        }

        #[test]
        fn tampered_sentinel_sequence_misses_the_total() {
            let leaf = poly(&[3, 5, 7, 11]);
            let beta = Fp::from(9);
            let zeta = subgroup_generator::<ORDER>();
            let (accumulator, _quotient) = evaluation_sum::<ORDER>(leaf.coefficients(), beta);
            let total = accumulator.eval(Fp::ONE);

            // Honest q: coefficient p is B(ζ^p), plus the sentinel at degree
            // ORDER; the discharge `q(β) − β^ORDER` recovers the total.
            let mut coeffs = vec![Fp::ZERO; ORDER + 1];
            let mut node = Fp::ONE;
            for slot in coeffs.iter_mut().take(ORDER) {
                *slot = leaf.eval(node);
                node *= zeta;
            }
            coeffs[ORDER] = Fp::ONE;
            let sentinel = power(beta, ORDER);
            assert_eq!(
                Polynomial::from_coeffs(&coeffs).eval(beta) - sentinel,
                total
            );

            // Flip one leaf coefficient: the discharge no longer matches.
            coeffs[0] += Fp::ONE;
            assert_ne!(
                Polynomial::from_coeffs(&coeffs).eval(beta) - sentinel,
                total
            );
        }

        #[test]
        fn tampered_accumulator_breaks_the_recurrence() {
            let leaf = poly(&[3, 5, 7, 11]);
            let beta = Fp::from(9);
            let (accumulator, quotient) = evaluation_sum::<ORDER>(leaf.coefficients(), beta);

            let mut coeffs = accumulator.coefficients().to_vec();
            coeffs[0] += Fp::ONE;
            let tampered = Polynomial::from_coeffs(&coeffs);
            assert!(!recurrence_holds(
                &leaf,
                &tampered,
                &quotient,
                beta,
                Fp::from(POINTS[2])
            ));
        }
    }
}
